# Generated by Django 2.2.16 on 2022-08-16 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20220816_2132'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='follow',
            name='posts_follo_user_id_13f95c_idx',
        ),
    ]
